//! `hf` — the .handoff continuity CLI (S1 spike).
//!
//! Implements the core of the .handoff "hard product standard": a fresh agent runs
//! `hf resume` and immediately knows project / objective / done / remaining / safe next
//! task / next command — no chat archaeology. Built on the validated `work-order` (the
//! handoff.task.v1 envelope) + `ledger` (rusqlite event store + rvf-crypto witness) crates.
//!
//! Verbs: init · seed · status · claim <id> · release <id> · checkpoint <id> [note] · handoff · resume [--json]
//! State precedence (tier 2/3): `.handoff/ledger.db` (events) > `.handoff/tasks/*.task.json` (cards).

mod lease;

use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use lease::Leaser;
use ledger::Ledger;
use work_order::{Priority, Status, WorkOrder};

const HF: &str = ".handoff";
/// TTL of a claim lease: a claim represents an active work session. Re-claiming
/// (heartbeat) extends it; `hf release` or expiry frees it.
const CLAIM_TTL_SECS: u64 = 3600;

fn now_ns() -> u64 {
    SystemTime::now().duration_since(UNIX_EPOCH).map(|d| d.as_nanos() as u64).unwrap_or(0)
}
fn tasks_dir() -> PathBuf { Path::new(HF).join("tasks") }
fn ledger_path() -> String { Path::new(HF).join("ledger.db").to_string_lossy().into_owned() }
fn packet_path() -> PathBuf { Path::new(HF).join("packets").join("latest.md") }
fn capsule_path() -> PathBuf { Path::new(HF).join("context").join("capsule.json") }

fn load_tasks() -> Vec<WorkOrder> {
    let mut v = vec![];
    if let Ok(rd) = fs::read_dir(tasks_dir()) {
        let mut paths: Vec<_> = rd.flatten().map(|e| e.path()).filter(|p| p.extension().map_or(false, |x| x == "json")).collect();
        paths.sort();
        for p in paths {
            if let Ok(s) = fs::read_to_string(&p) {
                if let Ok(wo) = serde_json::from_str::<WorkOrder>(&s) { v.push(wo); }
            }
        }
    }
    v
}
fn save_task(wo: &WorkOrder) {
    let _ = fs::create_dir_all(tasks_dir());
    let _ = fs::write(tasks_dir().join(format!("{}.task.json", wo.id)), wo.to_json());
}

/// Replay the ledger to get the current status per task id (overrides the card's stored status).
fn current_statuses() -> Vec<(String, Status)> {
    Ledger::open(&ledger_path()).and_then(|l| l.replay_latest_status()).unwrap_or_default()
}
fn status_of(id: &str, replay: &[(String, Status)], card: &WorkOrder) -> Status {
    replay.iter().find(|(k, _)| k == id).map(|(_, s)| *s).unwrap_or(card.status)
}

/// Next safe task: resume the in-progress task first (Claimed/Checkpointed/Active);
/// else the first backlog card whose dependencies are all Done.
fn next_safe<'a>(tasks: &'a [WorkOrder], replay: &[(String, Status)]) -> Option<&'a WorkOrder> {
    let done = |id: &str| replay.iter().any(|(k, s)| k == id && *s == Status::Done);
    // 1) an already-claimed/checkpointed/active task is the one to resume
    if let Some(t) = tasks.iter().find(|t| matches!(status_of(&t.id, replay, t),
        Status::Claimed | Status::Checkpointed | Status::Active | Status::Review)) {
        return Some(t);
    }
    // 2) otherwise the first backlog task whose deps are all Done
    tasks.iter().find(|t| {
        status_of(&t.id, replay, t) == Status::Backlog && t.dependencies.iter().all(|d| done(d))
    })
}

fn cmd_init() {
    for d in ["tasks", "packets", "context", "decisions"] { let _ = fs::create_dir_all(Path::new(HF).join(d)); }
    let _ = Ledger::open(&ledger_path()); // creates schema
    let _ = fs::write(Path::new(HF).join("active.md"), "# Active\n\n(generated by `hf handoff`)\n");
    let capsule = serde_json::json!({
        "schema": "handoff.context_capsule.v1",
        "project_name": "handoff (Continuity Ledger Kernel)",
        "northstar": "Adopt RuVector as the foundation; wire the .handoff contract onto existing crates.",
        "next_command": "hf resume"
    });
    let _ = fs::write(capsule_path(), serde_json::to_string_pretty(&capsule).unwrap());
    println!("hf init: created {}/ (ledger, tasks, packets, context)", HF);
}

fn cmd_claim(id: &str) {
    cmd_claim_with(id, &lease::WeaveCli::from_env());
}

/// Mesh-coordinated claim: reserve a weave lease on the task *before* recording the
/// ledger transition, so two sessions can't claim the same task. Refuses the claim
/// if another peer holds it; degrades to ledger-only when no weave mesh is present.
fn cmd_claim_with(id: &str, leaser: &dyn lease::Leaser) {
    let tasks = load_tasks();
    let Some(wo) = tasks.iter().find(|t| t.id == id) else { eprintln!("no such task {id}"); return };
    let resource = lease::claim_resource(id);
    match lease::gate(leaser.reserve(&resource, CLAIM_TTL_SECS, &format!("hf claim {id}"))) {
        lease::ClaimGate::Refuse(reason) => {
            eprintln!("hf claim: {id} BLOCKED — {resource} is held by another peer ({reason}); not claiming");
            return;
        }
        lease::ClaimGate::ProceedDegraded => {
            eprintln!("hf claim: weave lease unavailable — proceeding ledger-only (no mesh coordination)");
        }
        lease::ClaimGate::Proceed => {
            println!("hf claim: reserved weave lease {resource} (ttl {CLAIM_TTL_SECS}s)");
        }
    }
    let mut led = Ledger::open(&ledger_path()).unwrap();
    led.record_transition(wo, Status::Claimed, now_ns()).unwrap();
    println!("hf claim: {id} -> claimed");
}

/// Release the weave lease held on a task's claim (mesh hygiene after handoff/abort).
fn cmd_release(id: &str) {
    let resource = lease::claim_resource(id);
    if lease::WeaveCli::from_env().release(&resource) {
        println!("hf release: freed weave lease {resource}");
    } else {
        eprintln!("hf release: no active lease {resource} held by you (or weave unavailable)");
    }
}

fn cmd_checkpoint(id: &str, note: &str) {
    let payload = serde_json::json!({ "id": id, "note": note }).to_string();
    let mut led = Ledger::open(&ledger_path()).unwrap();
    led.append("checkpoint", id, &payload, now_ns()).unwrap();
    println!("hf checkpoint: {id} :: {note}");
}

fn cmd_status() {
    let tasks = load_tasks();
    let replay = current_statuses();
    println!("=== hf status ===  ({} tasks)", tasks.len());
    for t in &tasks {
        println!("  {:<12} {:<12} {:?}  {}", t.id, format!("{:?}", status_of(&t.id, &replay, t)), t.priority, t.title);
    }
    if let Some(n) = next_safe(&tasks, &replay) { println!("next safe: {} — {}", n.id, n.title); }
}

fn cmd_handoff() {
    let tasks = load_tasks();
    let replay = current_statuses();
    let done: Vec<_> = tasks.iter().filter(|t| status_of(&t.id, &replay, t) == Status::Done).collect();
    let remaining: Vec<_> = tasks.iter().filter(|t| status_of(&t.id, &replay, t) != Status::Done).collect();
    let next = next_safe(&tasks, &replay);
    let witness = Ledger::open(&ledger_path()).and_then(|l| l.verify_witness_chain()).unwrap_or(0);

    let summary = serde_json::json!({
        "schema": "handoff.packet.v2",
        "project": "handoff (Continuity Ledger Kernel)",
        "tasks_total": tasks.len(),
        "done": done.iter().map(|t| &t.id).collect::<Vec<_>>(),
        "remaining": remaining.iter().map(|t| &t.id).collect::<Vec<_>>(),
        "next_task_id": next.map(|t| &t.id),
        "witnessed_events_verified": witness,
        "next_command": next.map(|t| format!("hf claim {} && hf start", t.id)).unwrap_or_else(|| "done".into()),
    });

    let mut md = String::new();
    md.push_str("# Handoff Packet (latest) — handoff.packet.v2\n\n");
    md.push_str("## 1. North Star\nAdopt RuVector as the foundation; wire the .handoff contract onto existing crates.\n\n");
    md.push_str("## 2. State Precedence\nGit > .handoff/ledger.db > tasks/*.task.json > active.md > this packet.\n\n");
    md.push_str(&format!("## 3. Progress\nDone: {}/{}.  Tamper-evident events verified: {}.\n\n", done.len(), tasks.len(), witness));
    md.push_str("## 4. Remaining (next safe first)\n");
    for t in &remaining { md.push_str(&format!("- [{}] **{}** — {}\n", t.priority_str(), t.id, t.title)); }
    md.push_str("\n## 5. Next Best Task\n");
    if let Some(n) = next { md.push_str(&format!("**{}** — {}\n  objective: {}\n", n.id, n.title, n.objective)); }
    md.push_str(&format!("\n## 6. Resume Commands\n```bash\nhf resume\n{}\n```\n", summary["next_command"].as_str().unwrap_or("")));
    md.push_str("\n## 7. Machine Summary\n```json\n");
    md.push_str(&serde_json::to_string_pretty(&summary).unwrap());
    md.push_str("\n```\n");

    let _ = fs::create_dir_all(Path::new(HF).join("packets"));
    let _ = fs::write(packet_path(), &md);
    let _ = fs::write(Path::new(HF).join("active.md"),
        format!("# Active\n\nNext: {}\nDone {}/{} · witness-verified {} events\n",
            next.map(|t| t.id.as_str()).unwrap_or("—"), done.len(), tasks.len(), witness));
    println!("hf handoff: wrote {} (verified {} witnessed events)", packet_path().display(), witness);
}

fn cmd_resume(json: bool) {
    let packet = fs::read_to_string(packet_path()).unwrap_or_default();
    if json {
        // emit the machine summary block if present, else recompute via handoff
        if let Some(start) = packet.find("```json") {
            if let Some(end) = packet[start + 7..].find("```") {
                println!("{}", &packet[start + 7..start + 7 + end].trim());
                return;
            }
        }
        println!("{{\"error\":\"run hf handoff first\"}}");
    } else if packet.is_empty() {
        println!("No packet yet. Run: hf handoff");
    } else {
        println!("{packet}");
    }
}

// helper for Priority display in markdown
trait PrioStr { fn priority_str(&self) -> &'static str; }
impl PrioStr for WorkOrder {
    fn priority_str(&self) -> &'static str {
        match self.priority { Priority::P0 => "P0", Priority::P1 => "P1", Priority::P2 => "P2", Priority::P3 => "P3" }
    }
}

/// Seed the REAL continuation backlog (the tasks to finish the .handoff kernel) as task cards.
fn cmd_seed() {
    let mk = |id: &str, title: &str, pri: Priority, obj: &str, deps: &[&str]| {
        let path_scope = vec!["spike/**".to_string(), "handoff/**".to_string()];
        let acceptance = vec![format!("{title}: implemented + cargo test green + checkpointed")];
        WorkOrder {
            schema: "handoff.task.v1".into(), id: id.into(), title: title.into(),
            status: Status::Backlog, priority: pri, objective: obj.into(),
            path_scope: path_scope.clone(),
            acceptance_criteria: acceptance.clone(),
            test_commands: vec!["cargo test".into()],
            dependencies: deps.iter().map(|s| s.to_string()).collect(),
            blocked_by: vec![], allows_network: false, allows_dependency_addition: true,
            correlation_id: "handoff-buildout".into(), role: Some("implementer".into()),
            intent_lock: WorkOrder::compute_intent_lock(obj, &path_scope, &acceptance),
        }
    };
    let backlog = vec![
        mk("HFTASK-0001", "Finalize naming + register kernel (Continuity Ledger Kernel)", Priority::P0,
           "Kernel relocated to ~/Desktop/meta/handoff (own repo). Remaining: rename package/docs to Continuity Ledger Kernel + drop Ark/V2 in PRD; create+push FlexNetOS/handoff GitHub repo.", &[]),
        mk("HFTASK-0002", "Wire weave leases into hf claim", Priority::P0,
           "Replace the ledger-only claim with a weave lease (reserve/heartbeat/release) so claims are mesh-coordinated; hf claim -> weave_lease_reserve.", &["HFTASK-0001"]),
        mk("HFTASK-0003", "Real prompt_hub SwarmBundle -> handoff.task.v1 dispatch", Priority::P0,
           "Depend on prompt_hub's real SwarmBundle (not the spike mirror); implement the front-door dispatch SwarmBundle->WorkOrder over the MCP seam.", &["HFTASK-0001"]),
        mk("HFTASK-0004", "ruvector-verified AgentContract proof at hf handoff", Priority::P1,
           "On hf handoff, prove the intent_lock/acceptance via ruvector-verified (Lean) AgentContract; block handoff on unproven completion.", &["HFTASK-0001"]),
        mk("HFTASK-0005", "hf drift audit gate", Priority::P1,
           "Implement hf drift: recompute intent_lock, detect out-of-scope edits (git), hard-fail handoff on drift.", &["HFTASK-0004"]),
        mk("HFTASK-0006", "RVF vector-native ledger v2", Priority::P1,
           "Schedule + implement the RVF (rvf-runtime) vector-native event ledger for semantic recall over session history; keep rusqlite+witness as v1 fallback.", &["HFTASK-0002","HFTASK-0003"]),
        // --- Loop v2 (ADR-0001): worktree-isolated, cycle-batched, review-gated shipping ---
        mk("HFTASK-0007", "hf session on meta_git_lib worktree engine + policy.toml + sync preflight", Priority::P0,
           "ADR-0001 §2 (Research R3): add `hf session start|end [--recycle]` by DEPENDING ON meta_git_lib (worktree::git_ops add/remove, worktree::store TTL/ephemeral registry, worktree::hooks fire_post_create/destroy, helpers::{resolve_branch,ensure_worktrees_in_gitignore}, snapshot capture/restore) rather than reimplementing; fall back to `meta git worktree` CLI if lib not wired. Off origin/<base_branch>; reserve a weave path-scope lease; emit session_start/session_end; recycle a fresh set on end. Dotdir is .handoff (canonical; .hf does not exist). Add `.handoff/policy.toml` (remote/loop/merge). MUST include a start-time preflight verifying tree/branch/remote sync, refusing on drift (prior weave-loop failure lesson). Depend only on current lease-capable weave; refuse legacy repowire/mcp-broker.", &["HFTASK-0002"]),
        mk("HFTASK-0008", "Branch/remote policy engine (develop<->master, clone/fork)", Priority::P1,
           "ADR-0001 §3: policy module resolving clone-vs-fork, base=develop, trunk=master. Enforce: branch off origin/<base> after fetch only, never push trunk directly, ff develop->trunk after merge. Fork model deferred behind remote.model=fork.", &["HFTASK-0007"]),
        mk("HFTASK-0009", "Batch checkout (3-5) + cycle counter -> hf ship (one squash commit/PR)", Priority::P1,
           "ADR-0001 §4: `hf claim --batch N` (up to cycle_flush=4) reserves a lease per task so the loop never stalls; ledger-derived cycle counter (checkpoints since session_start) surfaced as cycles:n/flush; at threshold next_command=hf ship. `hf ship` = add + ONE squash commit listing all HFTASK ids -> push branch -> gh pr create --base trunk, emit pr_opened. Outward action is permission-gated and retryable, never a hard wall.", &["HFTASK-0007","HFTASK-0008"]),
        mk("HFTASK-0010", "PR review/merge automation - phased cloud_ultra->swarm_local + gh-aw guardrails", Priority::P1,
           "ADR-0001 §5/§5a (Research R4=gh-aw): reviewer is always a separate role (merge.reviewer). Phase 1 cloud_ultra: `hf review request <pr#>` runs /code-review ultra, records approve/deny via weave review (WL-020)+permission (WL-021). Phase 2 swarm_local: ruvector/ruflo (rvAgent) swarm reviewer. GUARDRAILS: (a) separation of privilege - worker agent read-only, a separate trusted scoped job does gh pr create/merge, agents never hold the merge token; (b) reviewer verdict OUT-OF-BAND in weave state, NOT a native GitHub APPROVE (bot-approval bypasses branch protection, gh-aw #25439); (c) merge is a non-agent Environment-gated job; (d) detection pass + protected-files denylist (.github/, .handoff/policy.toml, ADRs, manifests) before any write; (e) draft PRs, least-privilege tokens. `hf merge <pr#>` merges only on approved+permission-granted (gh pr merge --squash), ff develop; deny reopens task; pending waits. permission_gate transitional. flexnetos_github_app (currently empty) is the candidate home for the trusted writer/merge-gate. VERDICT CHANNEL (Research R6): weave review (WL-020) has NO verdict field - carry approve/deny in the weave permission (WL-021) answer body + a review_verdict event in hf's own ledger; hf enforces the gate (weave only records). Phase-2 swarm reviewer (Research R5): reuse rvAgent A2A transport + ApprovalDecision/GateResult types but BUILD the N-reviewers->one-verdict reducer (~50-100 LOC); spawn via process-level rvagent a2a serve (spawn_sync is a stub).", &["HFTASK-0009"]),
        mk("HFTASK-0011", "hf sync — idempotent .meta.yaml/.gitignore repair + one-way .kb mirror", Priority::P2,
           "ADR-0001 §6 (Research R7): Part A is IDEMPOTENT ensure/repair (handoff is ALREADY in ../.meta.yaml + ../.gitignore - there is a dup gitignore line to clean; no `meta project add` exists so grep-guard file edits, never blind append). Part B: git kb has NO upsert - do show-or-create -> checkout -> full-overwrite -> commit, scoped to context/overridable/active + context/overridable/progress (preserve frontmatter id; never rm+recreate). ONE-WAY: write only those generated slugs from a ledger-derived body, never read .kb back as truth, tag generated, never touch immutable/extensible/tasks slugs. Emit meta_registered; run at session end / post pr_merged.", &["HFTASK-0007"]),
    ];
    for wo in &backlog { save_task(wo); }
    println!("hf seed: wrote {} continuation task cards to {}/", backlog.len(), tasks_dir().display());
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.first().map(|s| s.as_str()) {
        Some("init") => cmd_init(),
        Some("seed") => cmd_seed(),
        Some("status") => cmd_status(),
        Some("claim") => cmd_claim(args.get(1).map(|s| s.as_str()).unwrap_or("")),
        Some("release") => cmd_release(args.get(1).map(|s| s.as_str()).unwrap_or("")),
        Some("checkpoint") => cmd_checkpoint(args.get(1).map(|s| s.as_str()).unwrap_or(""), &args[2..].join(" ")),
        Some("handoff") => cmd_handoff(),
        Some("resume") => cmd_resume(args.iter().any(|a| a == "--json")),
        _ => {
            eprintln!("hf <init|seed|status|claim ID|release ID|checkpoint ID [note]|handoff|resume [--json]>");
        }
    }
}
