//! `hf` — the .handoff continuity CLI (S1 spike).
//!
//! Implements the core of the .handoff "hard product standard": a fresh agent runs
//! `hf resume` and immediately knows project / objective / done / remaining / safe next
//! task / next command — no chat archaeology. Built on the validated `work-order` (the
//! handoff.task.v1 envelope) + `ledger` (rusqlite event store + rvf-crypto witness) crates.
//!
//! Verbs: init · seed · status · claim <id> · release <id> · checkpoint <id> [note] · handoff · resume [--json]
//!        · ship <id> [--base BRANCH] · review verdict <id> <pr> <approve|deny> [--by WHO]
//! State precedence (tier 2/3): `.handoff/ledger.db` (events) > `.handoff/tasks/*.task.json` (cards).

mod fleet;
mod gates;
mod intake;
mod kb;
mod lease;
mod policy;
mod route;
mod session;
mod sync;
#[cfg(test)]
mod test_support;

use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use lease::Leaser;
use ledger::Ledger;
use work_order::{Priority, Status, WorkOrder};

const HF: &str = ".handoff";
/// TTL of a claim lease: a claim represents an active work session. Re-claiming
/// (heartbeat) extends it; `hf release` or expiry frees it.
const CLAIM_TTL_SECS: u64 = 3600;

fn now_ns() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0)
}
fn tasks_dir() -> PathBuf {
    Path::new(HF).join("tasks")
}
fn ledger_path() -> String {
    Path::new(HF)
        .join("ledger.db")
        .to_string_lossy()
        .into_owned()
}
fn packet_path() -> PathBuf {
    Path::new(HF).join("packets").join("latest.md")
}
fn capsule_path() -> PathBuf {
    Path::new(HF).join("context").join("capsule.json")
}

fn load_tasks() -> Vec<WorkOrder> {
    let mut v = vec![];
    if let Ok(rd) = fs::read_dir(tasks_dir()) {
        let mut paths: Vec<_> = rd
            .flatten()
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|x| x == "json"))
            .collect();
        paths.sort();
        for p in paths {
            if let Ok(s) = fs::read_to_string(&p) {
                if let Ok(wo) = serde_json::from_str::<WorkOrder>(&s) {
                    v.push(wo);
                }
            }
        }
    }
    v
}
fn save_task(wo: &WorkOrder) {
    save_task_in(&tasks_dir(), wo);
}
/// Save a card into an explicit tasks dir (routing-aware: a per-task op writes the
/// card to the same home as the ledger it appends to — ADR-0004 §3). Creates the dir.
fn save_task_in(tasks_dir: &Path, wo: &WorkOrder) {
    let _ = fs::create_dir_all(tasks_dir);
    let _ = fs::write(tasks_dir.join(format!("{}.task.json", wo.id)), wo.to_json());
}
/// Load the card for one id from an explicit tasks dir (routing-aware read for the
/// resolved home, so per-task ops see the card that lives where the ledger lives).
fn load_task_in(tasks_dir: &Path, id: &str) -> Option<WorkOrder> {
    let p = tasks_dir.join(format!("{id}.task.json"));
    let s = fs::read_to_string(p).ok()?;
    serde_json::from_str::<WorkOrder>(&s).ok()
}

/// Replay the ledger to get the current status per task id (overrides the card's stored status).
fn current_statuses() -> Vec<(String, Status)> {
    Ledger::open(&ledger_path())
        .and_then(|l| l.replay_latest_status())
        .unwrap_or_default()
}
fn status_of(id: &str, replay: &[(String, Status)], card: &WorkOrder) -> Status {
    replay
        .iter()
        .find(|(k, _)| k == id)
        .map(|(_, s)| *s)
        .unwrap_or(card.status)
}

/// Next safe task: resume the in-progress task first (Claimed/Checkpointed/Active);
/// else the first backlog card whose dependencies are all Done.
fn next_safe<'a>(tasks: &'a [WorkOrder], replay: &[(String, Status)]) -> Option<&'a WorkOrder> {
    let done = |id: &str| replay.iter().any(|(k, s)| k == id && *s == Status::Done);
    // 1) an already-claimed/checkpointed/active task is the one to resume
    if let Some(t) = tasks.iter().find(|t| {
        matches!(
            status_of(&t.id, replay, t),
            Status::Claimed | Status::Checkpointed | Status::Active | Status::Review
        )
    }) {
        return Some(t);
    }
    // 2) otherwise the first backlog task whose deps are all Done
    tasks.iter().find(|t| {
        status_of(&t.id, replay, t) == Status::Backlog && t.dependencies.iter().all(|d| done(d))
    })
}

fn cmd_init() {
    for d in ["tasks", "packets", "context", "decisions"] {
        let _ = fs::create_dir_all(Path::new(HF).join(d));
    }
    let _ = Ledger::open(&ledger_path()); // creates schema
    let _ = fs::write(
        Path::new(HF).join("active.md"),
        "# Active\n\n(generated by `hf handoff`)\n",
    );
    let capsule = serde_json::json!({
        "schema": "handoff.context_capsule.v1",
        "project_name": "handoff (Continuity Ledger Kernel)",
        "northstar": "KERNEL DOCTRINE — build a local-first, auditable, reversible, model-native agentic OS where every agent action increases verified capability without corrupting the baseline: Integrity · Reversibility · Capability Gain (no promotion without all three). CECCA/NOA is the executive kernel; the Gold World is the protected baseline; failures compress into evidence. Authoritative: NORTH-STAR.md · keystone docs/adr-0001-flexnetos-autopilot-keystone.md. FLEET VISION (the why): NO HUMAN IN THE LOOP — multi-provider autopilot; user directs, system builds/operates; NEEDS-HUMAN is a scaffold replaced by a model with the human's skillset; end-state = single-person conglomerate. See ../NORTH-STAR.md · ../ARCHITECTURE-TRUTH.md · ../RUVECTOR-RUNBOOK.md",
        "next_command": "hf resume"
    });
    let _ = fs::write(
        capsule_path(),
        serde_json::to_string_pretty(&capsule).unwrap(),
    );
    println!("hf init: created {}/ (ledger, tasks, packets, context)", HF);
}

/// CLI entry for `hf claim <ID>`: exits nonzero when the claim is refused/blocked so
/// callers (hooks, scripts, the loop) see the failure (HFTASK-0029 Defect C). The
/// internal dispatch loop (intake.rs) calls `cmd_claim_with` directly and inspects the
/// bool instead, so it can skip a blocked order without aborting the whole process.
fn cmd_claim(id: &str) {
    if !cmd_claim_with(id, &lease::WeaveCli::from_env()) {
        std::process::exit(1);
    }
}

/// Mesh-coordinated claim: reserve a weave lease on the task *before* recording the
/// ledger transition, so two sessions can't claim the same task. Refuses the claim
/// if another peer holds it; degrades to ledger-only when no weave mesh is present.
///
/// Returns `true` when the task was claimed, `false` when the claim was refused/blocked
/// (HFTASK-0029 Defect C) — the CLI path turns `false` into a nonzero exit; the dispatch
/// loop uses the bool to skip-and-continue.
fn cmd_claim_with(id: &str, leaser: &dyn lease::Leaser) -> bool {
    let (ledger, tasks_dir) = match route::route_for_task(id) {
        Ok(homes) => homes,
        Err(e) => {
            eprintln!("{e}");
            std::process::exit(1);
        }
    };
    let Some(wo) = load_task_in(&tasks_dir, id) else {
        eprintln!("no such task {id}");
        std::process::exit(1);
    };
    let resource = lease::claim_resource(id);
    match lease::gate(leaser.reserve(&resource, CLAIM_TTL_SECS, &format!("hf claim {id}"))) {
        lease::ClaimGate::Refuse(reason) => {
            eprintln!("hf claim: {id} BLOCKED — {resource} is held by another peer ({reason}); not claiming");
            return false;
        }
        lease::ClaimGate::ProceedDegraded => {
            eprintln!(
                "hf claim: weave lease unavailable — proceeding ledger-only (no mesh coordination)"
            );
        }
        lease::ClaimGate::Proceed => {
            println!("hf claim: reserved weave lease {resource} (ttl {CLAIM_TTL_SECS}s)");
        }
    }
    let mut led = Ledger::open(&ledger.to_string_lossy()).unwrap();
    led.record_transition(&wo, Status::Claimed, now_ns())
        .unwrap();
    println!("hf claim: {id} -> claimed");
    true
}

/// Release the weave lease held on a task's claim (mesh hygiene after handoff/abort).
fn cmd_release(id: &str) {
    let resource = lease::claim_resource(id);
    if lease::WeaveCli::from_env().release(&resource) {
        println!("hf release: freed weave lease {resource}");
    } else {
        eprintln!("hf release: no active lease {resource} held by you (or weave unavailable)");
    }
}

/// `hf checkpoint <ID> [note]` — or `--auto` to checkpoint the current active task (the
/// resume target), `--quiet` to suppress stdout (for hook callers). Rejects a missing or
/// flag-shaped id so a malformed invocation can't pollute the witnessed ledger.
fn cmd_checkpoint(id: Option<&str>, note: &str, auto: bool, quiet: bool) {
    let resolved = if auto {
        let tasks = load_tasks();
        let replay = current_statuses();
        next_safe(&tasks, &replay).map(|t| t.id.clone())
    } else {
        id.map(|s| s.to_string())
    };
    let Some(id) = resolved else {
        eprintln!(
            "hf checkpoint: no task id — use `hf checkpoint <ID> [note]`, or `--auto` with an active task"
        );
        return;
    };
    if id.is_empty() || id.starts_with("--") {
        eprintln!("hf checkpoint: invalid task id '{id}'");
        return;
    }
    let note = if note.trim().is_empty() && auto {
        "auto checkpoint"
    } else {
        note
    };
    // Route the checkpoint to the home its task lives in (KERNEL vs FLEET). The
    // `--auto` path already resolved `id` from the LOCAL backlog, so it routes
    // local; an explicit `checkpoint <ID>` for a FLEET-resident task routes FLEET.
    let ledger = match route::route_for_task(&id) {
        Ok((ledger, _tasks)) => ledger,
        Err(e) => {
            eprintln!("{e}");
            std::process::exit(1);
        }
    };
    let payload = serde_json::json!({ "id": id, "note": note }).to_string();
    let mut led = Ledger::open(&ledger.to_string_lossy()).unwrap();
    led.append("checkpoint", &id, &payload, now_ns()).unwrap();
    if !quiet {
        println!("hf checkpoint: {id} :: {note}");
    }
}

/// `hf done <id> [--pr N]` — record the terminal `Done` transition (the loop's completion
/// signal, previously missing: claim→Claimed and checkpoint is a non-status event, so nothing
/// ever marked a task Done). With `--pr`, also witnesses a `pr_merged` event (ADR-0003 terminal).
fn cmd_done(id: &str, pr: Option<&str>) {
    if id.is_empty() {
        eprintln!("usage: hf done <task-id> [--pr N]");
        return;
    }
    let (ledger, tasks_dir) = match route::route_for_task(id) {
        Ok(homes) => homes,
        Err(e) => {
            eprintln!("{e}");
            std::process::exit(1);
        }
    };
    let Some(wo) = load_task_in(&tasks_dir, id) else {
        eprintln!("hf done: no such task {id}");
        std::process::exit(1);
    };
    let mut led = Ledger::open(&ledger.to_string_lossy()).unwrap();
    led.record_transition(&wo, Status::Done, now_ns()).unwrap();
    if let Some(p) = pr {
        let payload = serde_json::json!({ "id": id, "pr": p }).to_string();
        let _ = led.append("pr_merged", id, &payload, now_ns());
    }
    println!(
        "hf done: {id} -> done{}",
        pr.map(|p| format!(" (pr {p})")).unwrap_or_default()
    );
}

/// Persist each card's ledger-replayed status into its `.task.json` (ADR-0003 single-registry
/// rule: cards are derived snapshots of ledger truth). Returns the number of cards changed.
/// This is the deterministic fix for D3 (cards stale at `backlog` despite ledger progress).
fn sync_cards() -> usize {
    let replay = current_statuses();
    let mut changed = 0;
    for mut wo in load_tasks() {
        let live = status_of(&wo.id, &replay, &wo);
        if live != wo.status {
            wo.status = live;
            save_task(&wo);
            changed += 1;
        }
    }
    changed
}

/// Run a subprocess with explicit argv (no shell), capturing trimmed stdout.
/// Mirrors the lease::WeaveCli discipline (ADR-0002): no shell, explicit args.
fn run_out(bin: &str, args: &[&str]) -> Result<String, String> {
    match std::process::Command::new(bin).args(args).output() {
        Ok(o) if o.status.success() => Ok(String::from_utf8_lossy(&o.stdout).trim().to_string()),
        Ok(o) => Err(format!(
            "{bin} {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&o.stderr).trim()
        )),
        Err(e) => Err(format!("{bin} not runnable: {e}")),
    }
}

/// The repo-relative path of a task card on disk (`.handoff/tasks/<ID>.task.json`).
/// Pure (no I/O) so the staging decision is unit-testable (HFTASK-0029 Defect A).
fn task_card_relpath(id: &str) -> String {
    format!("{HF}/tasks/{id}.task.json")
}

/// The exact git pathspecs `hf ship` stages for a task — and ONLY these (HFTASK-0029
/// Defect A). `git add -u` stages tracked modifications/deletions but NO untracked files;
/// the task's own card is added explicitly (it may be newly created/seeded) when present.
/// Untracked scratch (_workspace/, stray cards) is deliberately excluded.
fn ship_stage_specs(id: &str) -> Vec<String> {
    let mut specs = vec!["-u".to_string()];
    let card = task_card_relpath(id);
    if Path::new(&card).exists() {
        specs.push(card);
    }
    specs
}

/// HFTASK-0009 core: one squash-style commit → push branch → PR → arm GitHub-native
/// auto-merge (HFTASK-0010 merge model: GitHub merges when ALL required checks are
/// green; hf never polls-and-merges and never overrides red). Emits `pr_opened`.
fn cmd_ship(id: &str, base: &str) {
    if id.is_empty() {
        eprintln!("usage: hf ship <task-id> [--base BRANCH]");
        return;
    }
    let branch = match run_out("git", &["branch", "--show-current"]) {
        Ok(b) if !b.is_empty() => b,
        _ => {
            eprintln!("hf ship: not on a branch (detached HEAD?) — refusing");
            return;
        }
    };
    if branch == base || branch == "master" || branch == "main" {
        eprintln!(
            "hf ship: refusing to ship from trunk '{branch}' — work happens on session branches"
        );
        return;
    }
    // single squash-style commit of the working tree (if dirty).
    // HFTASK-0029 Defect A: stage ONLY task scope — `git add -u` (tracked
    // modifications/deletions, NO untracked files) plus the task's own card (which may be
    // newly created/seeded). This stops untracked scratch (_workspace/, stray KBTASK cards)
    // from being swept into the PR (PR #29 regression).
    let dirty = run_out("git", &["status", "--porcelain"]).unwrap_or_default();
    if !dirty.is_empty() {
        for spec in ship_stage_specs(id) {
            if let Err(e) = run_out("git", &["add", &spec]) {
                eprintln!("hf ship: {e}");
                return;
            }
        }
        let msg = format!(
            "feat: ship {id}

Shipped via `hf ship` (handoff.task.v1 {id}).

Implements [[tasks/{id}]]"
        );
        if let Err(e) = run_out("git", &["commit", "-m", &msg]) {
            eprintln!("hf ship: {e}");
            return;
        }
        println!("hf ship: committed working tree on {branch}");
    }
    if let Err(e) = run_out("git", &["push", "-u", "origin", &branch]) {
        eprintln!("hf ship: push failed — {e}");
        return;
    }
    println!("hf ship: pushed {branch}");
    // PR create (idempotent: reuse an existing open PR for this branch)
    let pr_url = match run_out(
        "gh",
        &["pr", "view", &branch, "--json", "url", "--jq", ".url"],
    ) {
        Ok(u) if u.starts_with("http") => {
            println!("hf ship: reusing open PR {u}");
            u
        }
        _ => {
            let title = format!("feat: ship {id}");
            let body = format!(
                "Shipped via `hf ship` (handoff.task.v1 **{id}**).\n\nAuto-merge is armed; GitHub merges when all required checks on `{base}` pass."
            );
            match run_out(
                "gh",
                &[
                    "pr", "create", "--base", base, "--head", &branch, "--title", &title, "--body",
                    &body,
                ],
            ) {
                Ok(u) => u.lines().last().unwrap_or_default().to_string(),
                Err(e) => {
                    eprintln!("hf ship: PR creation failed — {e}");
                    return;
                }
            }
        }
    };
    println!("hf ship: PR {pr_url}");
    // arm GitHub-native auto-merge — non-fatal (e.g. unprotected base merges need no arming)
    match run_out("gh", &["pr", "merge", "--auto", "--squash", &pr_url]) {
        Ok(_) => {
            println!("hf ship: native auto-merge armed (squash) — GitHub completes on green checks")
        }
        Err(e) => {
            eprintln!("hf ship: auto-merge not armed ({e}) — merge manually or via review flow")
        }
    }
    let ledger = match route::route_for_task(id) {
        Ok((ledger, _tasks)) => ledger,
        Err(e) => {
            eprintln!("{e}");
            std::process::exit(1);
        }
    };
    let payload =
        serde_json::json!({ "id": id, "branch": branch, "pr": pr_url, "base": base }).to_string();
    let mut led = Ledger::open(&ledger.to_string_lossy()).unwrap();
    led.append("pr_opened", id, &payload, now_ns()).unwrap();
    println!("hf ship: pr_opened recorded for {id}");
}

/// HFTASK-0010 verdict channel (R6): verdicts ride OUT-OF-BAND — a weave permission
/// answer carries approve/deny, and hf records `review_verdict` in its own witnessed
/// ledger. Never a native GitHub APPROVE (bot-approval bypasses branch protection).
fn cmd_review_verdict(id: &str, pr: &str, verdict: &str, by: &str) {
    if id.is_empty() || pr.is_empty() || !matches!(verdict, "approve" | "deny") {
        eprintln!("usage: hf review verdict <task-id> <pr> <approve|deny> [--by WHO]");
        return;
    }
    let ledger = match route::route_for_task(id) {
        Ok((ledger, _tasks)) => ledger,
        Err(e) => {
            eprintln!("{e}");
            std::process::exit(1);
        }
    };
    let payload =
        serde_json::json!({ "id": id, "pr": pr, "verdict": verdict, "by": by }).to_string();
    let mut led = Ledger::open(&ledger.to_string_lossy()).unwrap();
    led.append("review_verdict", id, &payload, now_ns())
        .unwrap();
    println!("hf review: {verdict} recorded for {id} ({pr}) by {by}");
}

/// Read a top-level string field from the context capsule (best-effort).
fn capsule_field(key: &str) -> Option<String> {
    let s = fs::read_to_string(capsule_path()).ok()?;
    let v: serde_json::Value = serde_json::from_str(&s).ok()?;
    v.get(key).and_then(|x| x.as_str()).map(String::from)
}

fn cmd_status(json: bool) {
    let tasks = load_tasks();
    let replay = current_statuses();
    if json {
        emit_status_json(&tasks, &replay);
        return;
    }
    println!("=== hf status ===  ({} tasks)", tasks.len());
    for t in &tasks {
        println!(
            "  {:<12} {:<12} {:?}  {}",
            t.id,
            format!("{:?}", status_of(&t.id, &replay, t)),
            t.priority,
            t.title
        );
    }
    if let Some(n) = next_safe(&tasks, &replay) {
        println!("next safe: {} — {}", n.id, n.title);
    }
}

/// HFTASK-0020: the loop's machine read-model (`handoff.loop_status.v1`) — the witnessed
/// ledger event stream rendered as JSON for Mission Control / the MCP seam / RuVocal.
fn emit_status_json(tasks: &[WorkOrder], replay: &[(String, Status)]) {
    let done = tasks
        .iter()
        .filter(|t| status_of(&t.id, replay, t) == Status::Done)
        .count();
    let next = next_safe(tasks, replay);
    let witness = Ledger::open(&ledger_path())
        .and_then(|l| l.verify_witness_chain())
        .unwrap_or(0);
    let sess = session::open_session_and_cycle();
    let policy = policy::Policy::load(Path::new(HF));
    let project = capsule_field("project_name")
        .unwrap_or_else(|| "handoff (Continuity Ledger Kernel)".into());

    let out = serde_json::json!({
        "schema": "handoff.loop_status.v1",
        "project": project,
        "tasks_total": tasks.len(),
        "done": done,
        "remaining": tasks.len() - done,
        "tasks": tasks.iter().map(|t| serde_json::json!({
            "id": t.id,
            "status": format!("{:?}", status_of(&t.id, replay, t)),
            "priority": t.priority_str(),
            "title": t.title,
        })).collect::<Vec<_>>(),
        "next_task_id": next.map(|t| t.id.clone()),
        "next_command": next.map(|t| format!("hf claim {}", t.id)).unwrap_or_else(|| "done".into()),
        "session": {
            "open": sess.open_branch.is_some(),
            "branch": sess.open_branch,
            "cycle": sess.cycle,
            "cycle_flush": policy.loop_cfg.cycle_flush,
            "ready_to_ship": sess.cycle >= policy.loop_cfg.cycle_flush,
        },
        "witnessed_events_verified": witness,
    });
    println!("{}", serde_json::to_string_pretty(&out).unwrap());
}

/// Build the handoff.packet.v2 machine summary from already-known facts. Pure over its
/// inputs (the witness count is computed by the caller) so it is unit-testable — this is
/// the single source for both the packet and `hf resume --json`.
fn summary_json(
    tasks: &[WorkOrder],
    replay: &[(String, Status)],
    witness: usize,
) -> serde_json::Value {
    let done: Vec<&String> = tasks
        .iter()
        .filter(|t| status_of(&t.id, replay, t) == Status::Done)
        .map(|t| &t.id)
        .collect();
    let remaining: Vec<&String> = tasks
        .iter()
        .filter(|t| status_of(&t.id, replay, t) != Status::Done)
        .map(|t| &t.id)
        .collect();
    let next = next_safe(tasks, replay);
    serde_json::json!({
        "schema": "handoff.packet.v2",
        "project": "handoff (Continuity Ledger Kernel)",
        "tasks_total": tasks.len(),
        "done": done,
        "remaining": remaining,
        "next_task_id": next.map(|t| &t.id),
        "witnessed_events_verified": witness,
        "next_command": next.map(|t| format!("hf claim {}", t.id)).unwrap_or_else(|| "done".into()),
    })
}

/// The live machine read-model, computed straight from the ledger + cards. Both `hf handoff`
/// and `hf resume --json` go through this, so resume never lags the ledger (FIX-2: resume
/// previously echoed the last packet, under-counting by any event appended since).
fn machine_summary(tasks: &[WorkOrder], replay: &[(String, Status)]) -> serde_json::Value {
    let witness = Ledger::open(&ledger_path())
        .and_then(|l| l.verify_witness_chain())
        .unwrap_or(0);
    summary_json(tasks, replay, witness)
}

/// Render the handoff.packet.v2 markdown from already-known facts. Pure over its inputs
/// (the witness count is computed by the caller) so both `hf handoff` (which persists it)
/// and `hf resume` (which renders it LIVE, never reading the frozen file) share one
/// renderer — guaranteeing resume's Done N/M + witness count agree with handoff
/// (HFTASK-0027: resume previously echoed the last-written packet, freezing the count at
/// the last `hf handoff`).
fn render_packet_md(tasks: &[WorkOrder], replay: &[(String, Status)], witness: usize) -> String {
    let done: Vec<_> = tasks
        .iter()
        .filter(|t| status_of(&t.id, replay, t) == Status::Done)
        .collect();
    let remaining: Vec<_> = tasks
        .iter()
        .filter(|t| status_of(&t.id, replay, t) != Status::Done)
        .collect();
    let next = next_safe(tasks, replay);
    let summary = summary_json(tasks, replay, witness);

    let mut md = String::new();
    md.push_str("# Handoff Packet (latest) — handoff.packet.v2\n\n");
    // North Star is rendered from the context capsule (ADR-0006 portability: no
    // hardcoded northstar in the renderer). The capsule points to the canonical
    // fleet vision/architecture/runbook docs at the meta root.
    let northstar = capsule_field("northstar").unwrap_or_else(|| {
        "See ../NORTH-STAR.md (canon). NO HUMAN IN THE LOOP: a multi-provider agentic autopilot \
         — the user gives direction, the system builds/verifies/delivers."
            .to_string()
    });
    md.push_str(&format!("## 1. North Star\n{northstar}\n\n"));
    md.push_str("## 2. State Precedence\nGit > .handoff/ledger.db > tasks/*.task.json > active.md > this packet.\n\n");
    md.push_str(&format!(
        "## 3. Progress\nDone: {}/{}.  Tamper-evident events verified: {}.\n\n",
        done.len(),
        tasks.len(),
        witness
    ));
    md.push_str("## 4. Remaining (next safe first)\n");
    for t in &remaining {
        md.push_str(&format!(
            "- [{}] **{}** — {}\n",
            t.priority_str(),
            t.id,
            t.title
        ));
    }
    md.push_str("\n## 5. Next Best Task\n");
    if let Some(n) = next {
        md.push_str(&format!(
            "**{}** — {}\n  objective: {}\n",
            n.id, n.title, n.objective
        ));
    }
    md.push_str(&format!(
        "\n## 6. Resume Commands\n```bash\nhf resume\n{}\n```\n",
        summary["next_command"].as_str().unwrap_or("")
    ));
    md.push_str("\n## 7. Machine Summary\n```json\n");
    md.push_str(&serde_json::to_string_pretty(&summary).unwrap());
    md.push_str("\n```\n");
    md
}

fn cmd_handoff() {
    let tasks = load_tasks();
    let replay = current_statuses();
    let done: Vec<_> = tasks
        .iter()
        .filter(|t| status_of(&t.id, &replay, t) == Status::Done)
        .collect();
    let next = next_safe(&tasks, &replay);
    let witness = Ledger::open(&ledger_path())
        .and_then(|l| l.verify_witness_chain())
        .unwrap_or(0);

    let md = render_packet_md(&tasks, &replay, witness);

    let _ = fs::create_dir_all(Path::new(HF).join("packets"));
    let _ = fs::write(packet_path(), &md);
    let _ = fs::write(
        Path::new(HF).join("active.md"),
        format!(
            "# Active\n\nNext: {}\nDone {}/{} · witness-verified {} events\n",
            next.map(|t| t.id.as_str()).unwrap_or("—"),
            done.len(),
            tasks.len(),
            witness
        ),
    );
    println!(
        "hf handoff: wrote {} (verified {} witnessed events)",
        packet_path().display(),
        witness
    );
}

enum ResumeMode {
    /// Full compiled packet (markdown read-model).
    Full,
    /// Live machine summary (recomputed from the ledger — never stale).
    Json,
    /// One-line live status for hooks / fast resume.
    Compact,
}

fn cmd_resume(mode: ResumeMode) {
    match mode {
        ResumeMode::Json => {
            let tasks = load_tasks();
            let replay = current_statuses();
            println!(
                "{}",
                serde_json::to_string_pretty(&machine_summary(&tasks, &replay)).unwrap()
            );
        }
        ResumeMode::Compact => {
            let tasks = load_tasks();
            let replay = current_statuses();
            let s = machine_summary(&tasks, &replay);
            let done = s["done"].as_array().map(|a| a.len()).unwrap_or(0);
            println!(
                "handoff: {done}/{} done · {} witnessed · next: {} → {}",
                s["tasks_total"],
                s["witnessed_events_verified"],
                s["next_task_id"].as_str().unwrap_or("—"),
                s["next_command"].as_str().unwrap_or(""),
            );
        }
        ResumeMode::Full => {
            // HFTASK-0027: render the packet LIVE from the ledger + cards instead of
            // echoing the frozen packets/latest.md (which freezes Done N/M + the
            // witnessed count at the last `hf handoff`). Same renderer as `hf handoff`,
            // so resume's numbers always equal handoff's and reflect events appended
            // since the last handoff.
            let tasks = load_tasks();
            let replay = current_statuses();
            let witness = Ledger::open(&ledger_path())
                .and_then(|l| l.verify_witness_chain())
                .unwrap_or(0);
            println!("{}", render_packet_md(&tasks, &replay, witness));
        }
    }
}

// helper for Priority display in markdown
trait PrioStr {
    fn priority_str(&self) -> &'static str;
}
impl PrioStr for WorkOrder {
    fn priority_str(&self) -> &'static str {
        match self.priority {
            Priority::P0 => "P0",
            Priority::P1 => "P1",
            Priority::P2 => "P2",
            Priority::P3 => "P3",
        }
    }
}

/// Seed the REAL continuation backlog (the tasks to finish the .handoff kernel) as task cards.
fn cmd_seed() {
    let mk = |id: &str, title: &str, pri: Priority, obj: &str, deps: &[&str]| {
        let path_scope = vec!["spike/**".to_string(), "handoff/**".to_string()];
        let acceptance = vec![format!(
            "{title}: implemented + cargo test green + checkpointed"
        )];
        WorkOrder {
            schema: "handoff.task.v1".into(),
            id: id.into(),
            title: title.into(),
            status: Status::Backlog,
            priority: pri,
            objective: obj.into(),
            path_scope: path_scope.clone(),
            acceptance_criteria: acceptance.clone(),
            test_commands: vec!["cargo test".into()],
            dependencies: deps.iter().map(|s| s.to_string()).collect(),
            blocked_by: vec![],
            allows_network: false,
            allows_dependency_addition: true,
            correlation_id: "handoff-buildout".into(),
            role: Some("implementer".into()),
            intent_lock: WorkOrder::compute_intent_lock(obj, &path_scope, &acceptance),
        }
    };
    let backlog = vec![
        mk("HFTASK-0001", "Finalize naming + register kernel (Continuity Ledger Kernel)", Priority::P0,
           "Kernel relocated to ~/Desktop/meta/handoff (own repo). Remaining: rename package/docs to Continuity Ledger Kernel + drop Ark/V2 in PRD; create+push FlexNetOS/handoff GitHub repo.", &[]),
        mk("HFTASK-0002", "Wire weave leases into hf claim", Priority::P0,
           "Replace the ledger-only claim with a weave lease (reserve/heartbeat/release) so claims are mesh-coordinated; hf claim -> weave_lease_reserve.", &["HFTASK-0001"]),
        mk("HFTASK-0003", "Front door: prompt_hub SwarmBundle -> verifiable handoff.task.v1 intake", Priority::P0,
           "ADR-0001 §11/R14 (verified): promote the spike - work_orders_from_bundle is test-only + uses a MIRRORED SwarmBundle; depend on prompt_hub's REAL SwarmBundle (models.rs:528) and wire it into a real `hf intake`/`hf dispatch` verb. TRANSPORT: there is NO MCP server on either side (prompt_hub or hf), so do NOT assume 'the MCP seam' - either call prompt_hub HTTP /vibe+/generate_bundle, depend on the prompt-hub crate, or build the seam (HFTASK-0019). CRUX: SwarmBundle role_prompts are prompt STRINGS (and empty-in-prod), not work specs - the intake must SYNTHESIZE a vibe Intent into REAL path_scope/acceptance_criteria/test_commands or every dispatched WorkOrder is unverifiable by the §5 review gate + §5b gatekeeper.", &["HFTASK-0001"]),
        mk("HFTASK-0004", "ruvector-verified AgentContract proof at hf handoff", Priority::P1,
           "On hf handoff, prove the intent_lock/acceptance via ruvector-verified (Lean) AgentContract; block handoff on unproven completion.", &["HFTASK-0001"]),
        mk("HFTASK-0005", "hf drift audit gate", Priority::P1,
           "Implement hf drift: recompute intent_lock, detect out-of-scope edits (git), hard-fail handoff on drift.", &["HFTASK-0004"]),
        mk("HFTASK-0006", "RVF vector-native ledger v2", Priority::P1,
           "Schedule + implement the RVF (rvf-runtime) vector-native event ledger for semantic recall over session history; keep rusqlite+witness as v1 fallback.", &["HFTASK-0002","HFTASK-0003"]),
        // --- Loop v2 (ADR-0001): worktree-isolated, cycle-batched, review-gated shipping ---
        mk("HFTASK-0007", "hf session on meta_git_lib worktree engine + policy.toml + sync preflight", Priority::P0,
           "ADR-0001 §2 (Research R3): add `hf session start|end [--recycle]` by DEPENDING ON meta_git_lib (worktree::git_ops add/remove, worktree::store TTL/ephemeral registry, worktree::hooks fire_post_create/destroy, helpers::{resolve_branch,ensure_worktrees_in_gitignore}, snapshot capture/restore) rather than reimplementing; fall back to `meta git worktree` CLI if lib not wired. Off origin/<base_branch>; reserve a weave path-scope lease; emit session_start/session_end; recycle a fresh set on end. Dotdir is .handoff (canonical; .hf does not exist). Add `.handoff/policy.toml` (remote/loop/merge). MUST include a start-time preflight verifying tree/branch/remote sync, refusing on drift (prior weave-loop failure lesson). Depend only on current lease-capable weave; refuse legacy repowire/mcp-broker.", &["HFTASK-0002"]),
        mk("HFTASK-0008", "Branch/remote policy engine (develop<->master, clone/fork)", Priority::P1,
           "ADR-0001 §3: policy module resolving clone-vs-fork, base=develop, trunk=master. Enforce: branch off origin/<base> after fetch only, never push trunk directly, ff develop->trunk after merge. Fork model deferred behind remote.model=fork.", &["HFTASK-0007"]),
        mk("HFTASK-0009", "Batch checkout (3-5) + cycle counter -> hf ship (one squash commit/PR)", Priority::P1,
           "ADR-0001 §4: `hf claim --batch N` (up to cycle_flush=4) reserves a lease per task so the loop never stalls; ledger-derived cycle counter (checkpoints since session_start) surfaced as cycles:n/flush; at threshold next_command=hf ship. `hf ship` = add + ONE squash commit listing all HFTASK ids -> push branch -> gh pr create --base trunk, emit pr_opened. Outward action is permission-gated and retryable, never a hard wall.", &["HFTASK-0007","HFTASK-0008"]),
        mk("HFTASK-0010", "PR review/merge automation - phased cloud_ultra->swarm_local + gh-aw guardrails", Priority::P1,
           "ADR-0001 §5/§5a (Research R4=gh-aw): reviewer is always a separate role (merge.reviewer). Phase 1 cloud_ultra: `hf review request <pr#>` runs /code-review ultra, records approve/deny via weave review (WL-020)+permission (WL-021). Phase 2 swarm_local: ruvector/ruflo (rvAgent) swarm reviewer. GUARDRAILS: (a) separation of privilege - worker agent read-only, a separate trusted scoped job does gh pr create/merge, agents never hold the merge token; (b) reviewer verdict OUT-OF-BAND in weave state, NOT a native GitHub APPROVE (bot-approval bypasses branch protection, gh-aw #25439); (c) merge is a non-agent Environment-gated job; (d) detection pass + protected-files denylist (.github/, .handoff/policy.toml, ADRs, manifests) before any write; (e) draft PRs, least-privilege tokens. MERGE MODEL (Research R11, rusty-idd-proven fail-closed): hf ship enables GitHub-NATIVE auto-merge `gh pr merge --auto --squash` against branch-protected trunk; GitHub merges when ALL required checks green, async, even after process exit. hf does NOT poll-and-merge or override red (red = wall). The §5b AI gatekeeper is a REQUIRED STATUS CHECK feeding branch protection (CI job posting a check-run), NOT an agent calling gh pr merge out-of-band. ff develop after merge; deny reopens task; pending waits. permission_gate transitional. flexnetos_github_app (currently empty) is the candidate home for the trusted writer/merge-gate. VERDICT CHANNEL (Research R6): weave review (WL-020) has NO verdict field - carry approve/deny in the weave permission (WL-021) answer body + a review_verdict event in hf's own ledger; hf enforces the gate (weave only records). Phase-2 swarm reviewer (Research R5): reuse rvAgent A2A transport + ApprovalDecision/GateResult types but BUILD the N-reviewers->one-verdict reducer (~50-100 LOC); spawn via process-level rvagent a2a serve (spawn_sync is a stub).", &["HFTASK-0009"]),
        mk("HFTASK-0011", "hf sync — idempotent .meta.yaml/.gitignore repair + one-way .kb mirror", Priority::P2,
           "ADR-0001 §6 (Research R7): Part A is IDEMPOTENT ensure/repair (handoff is ALREADY in ../.meta.yaml + ../.gitignore - there is a dup gitignore line to clean; no `meta project add` exists so grep-guard file edits, never blind append). Part B: git kb has NO upsert - do show-or-create -> checkout -> full-overwrite -> commit, scoped to context/overridable/active + context/overridable/progress (preserve frontmatter id; never rm+recreate). ONE-WAY: write only those generated slugs from a ledger-derived body, never read .kb back as truth, tag generated, never touch immutable/extensible/tasks slugs. Emit meta_registered; run at session end / post pr_merged.", &["HFTASK-0007"]),
        mk("HFTASK-0012", "CI/CD bring-up - workflows + branch protection + merge-gate Environment", Priority::P1,
           "ADR-0001 §9 (Research R8): handoff has NO .github/ yet and isn't pushed. Add canonical workflows .github/workflows/{ci,auto-format,notify-parent}.yml (ci jobs test/clippy/format/build with RUSTFLAGS=-D warnings, CARGO_TERM_COLOR; least-privilege permissions: top-level contents:read, escalate per-job; auto-format loop-guarded). Turn on REAL branch protection on trunk (required checks test/clippy/format/build, strict=true up-to-date, enforce_admins deliberate, native required-reviews OFF to avoid the bot-APPROVE bypass #25439). Create a GitHub Environment 'merge-gate' (org has ZERO today) with required reviewers + env-scoped secrets = the infra that makes §5 permission-gated merge real and the human->swarm flip a config change. Join the repository_dispatch mesh (child-repo-updated to FlexNetOS/meta after CI green, SHA-pinned actions). Split overloaded PARENT_REPO_PAT into scoped fine-grained PATs; prefer GitHub App/OIDC (flexnetos_github_app is the home).", &["HFTASK-0001"]),
        mk("HFTASK-0013", "Integrate envctl secrets-engine as the secret relay/injection layer", Priority::P1,
           "ADR-0001 §9.5/R10: replace long-lived PARENT_REPO_PAT with envctl secrets-engine (~/Desktop/meta/envctl/crates/secrets-engine). Worker gets only a short-lived peer-bound revocable relay bearer (relay_mint, <=24h); real GitHub credential stays in the encrypted vault, swapped at egress (relay_swap). Use broker::decide (pure default-deny: host/path/method allowlists, budgets, fail-closed presence gate) as the deterministic merge-gate enforcement layer beneath the §5b AI gatekeeper. Surface: Engine Rust API / secretd gRPC (Relay.Mint) / secretctl. GREENFIELD to build: GitHub ProviderMint (native scoped sub-token, currently NoMint) + inject.rs/run_child child-env path (todo!, Phase 6/8); relay-bearer+relay_swap HTTP path works now.", &["HFTASK-0010"]),
        mk("HFTASK-0014", "Surgical AI gatekeeper with full code knowledge (replaces human approvals)", Priority::P1,
           "ADR-0001 §5b: the end-state merge approver is a code-OMNISCIENT AI gatekeeper (not human, not blind swarm). REQUIRES full-codebase code intelligence (git kb code index / kb_callers/kb_impact, and/or RuVector) so it judges a change against its full blast radius (callers/callees/invariants), not just the diff. It is the swarm_local reviewer (HFTASK-0010) upgraded with mandatory full-code grounding. Verdict=judgment; envctl broker::decide (HFTASK-0013) is the deterministic enforcement that actually releases the token/merge. permission_gate is transitional toward THIS gatekeeper, not toward a human; remove the human approver once gatekeeper+broker are trusted.", &["HFTASK-0010","HFTASK-0013"]),
        mk("HFTASK-0015", "hf policy engine + hook contract wiring (lifecycle automation)", Priority::P1,
           "ADR-0001 §10/R9: implement `hf policy check-claim|check-edit|check-handoff` reading the brought-forward .handoff/policies/rules.toml (handoff.policy.rules.v1: deny-without-claim, lease timings, drift blocks, protected-files denylist, blocked commands). Wire .handoff/hooks/hooks.toml (handoff.hooks.v1) so the agent harness fires hf on SessionStart/PreSessionStart(preflight)/TaskClaim/PreEdit/PostEdit/PreHandoff/SessionStop/PostMerge with fail_mode block as hard gates. This is the no-human-in-the-loop automation substrate. Reconcile lease heartbeat/stale/force-release timings with HFTASK-0002 claim TTL.", &["HFTASK-0007"]),
        mk("HFTASK-0016", "Adopt FlexNetOS meta conventions (avoid rusty-idd's drift)", Priority::P2,
           "ADR-0001 §9.6/R12 (3 rusty-idd-vs-meta drift reports, spot-verified in ~/Desktop/meta): handoff is a meta member and lacks the org convention set. Add: commitlint.config.cjs (12 types) + semantic-pr-title.yml (merge-blocking); release-please manifest mode + VERSION file + 5-platform release.yml (NOT cargo-dist); renovate.json (NOT Dependabot - D3); .githooks/{commit-msg,pre-commit,pre-push} + make install-hooks (NOT python pre-commit - D4); Makefile (NOT Justfile - D7); .claude/agent-guard.toml + settings.json hooks + .claude/rules/; 3-OS CI matrix + Swatinem/rust-cache + pinned toolchain (1.96.0); CONTRIBUTING.md. ALSO adopt rusty-idd's two-tier promote-verify (develop->main gate: clean-merge probe + locked build/test + drift + fmt/clippy + cargo audit --deny warnings) into §9 CI. ALREADY DONE: handoff is in .meta.yaml (rusty-idd's D5). Avoid the promote-verify.yml duplicate-run: bug (R11).", &["HFTASK-0012"]),
        // --- RuVector coverage gaps (ADR-0001 R13) + front door / mission control / delivery (R14) ---
        mk("HFTASK-0017", "cognitum-gate as the witnessed hf policy decision engine", Priority::P2,
           "ADR-0001 R13: HFTASK-0015 uses a flat rules.toml denylist; the runbook (S1 §2) mapped the policy gate to RuVector's cognitum-gate-tilezero (decision.rs GateDecision{Permit,Defer,Deny} + WitnessReceipt). Adopt cognitum-gate as the in-loop ACTION governor (what an agent may DO) behind `hf policy`, emitting witnessed permit/deny/defer. Distinct from the envctl broker (R10 = secret/credential+merge egress gate); they compose (action gate + credential gate). Verified crate exists at ~/Desktop/meta/RuVector/crates/cognitum-gate-tilezero.", &["HFTASK-0015"]),
        mk("HFTASK-0018", "ruvector-domain-expansion next-task routing (highest-value safe task)", Priority::P2,
           "ADR-0001 R13: the loop currently picks the next task by dependency order only (next_safe). Adopt RuVector's ruvector-domain-expansion (contextual routing / Thompson-style selection, S1:37) so hf claim --batch selects the highest-value safe tasks per context, not just topological order - core to an autonomous loop. Verified crate exists; capability claim (bandit/Thompson) from the runbook walk, re-verify symbols before building.", &["HFTASK-0009"]),
        mk("HFTASK-0019", "Expose hf as an MCP server (the T11 universal control seam)", Priority::P1,
           "ADR-0001 R13/§11: the runbook's T11 = MCP is the universal control seam; every RuVector subsystem is MCP-accessible but hf is not, and NO MCP server exists on the prompt_hub side either (R14 verified). Expose hf verbs (status/resume/claim/ship/review/intake...) as an MCP server so chat->MCP->work-order dispatch has a handoff-side endpoint, and the front door (HFTASK-0003) can dispatch over a real seam (pattern: rvAgent rvagent-mcp / mcp-gate / mcp-brain).", &["HFTASK-0007"]),
        mk("HFTASK-0020", "Mission Control - loop observability (hf status --json / hf watch + render)", Priority::P1,
           "ADR-0001 §12/R14: NO existing UI surfaces the handoff loop's live state ('mission control' currently = envctl's zellij layout generator - naming collision). The witnessed ledger event stream (§7) IS the read-model. Build `hf status --json` + `hf watch` (tail ledger + weave broadcasts; optional SSE) as the machine feed; surface the existing control verbs (resume, review request, weave permission answer, hf merge --confirm, abort). Render layer greenfield: reuse envctl-gui egui pattern or a TUI (prompt_hub has ratatui) first cut. Disambiguate workspace-mission-control vs loop-mission-control.", &["HFTASK-0007"]),
        mk("HFTASK-0021", "Delivery / output endpoint (correlation_id round-trip to front door)", Priority::P2,
           "ADR-0001 §13/R14: the pipeline is prompt_hub(input)->process->delivery(output) but the output endpoint was absent. correlation_id (=prompt_hub workflow_id) is already carried on every WorkOrder, so round-trip a merged cycle's result back to the originating vibe request - surfaced in RuVocal chat or via prompt_hub summarize <run-id>/feedback. Emit on pr_merged.", &["HFTASK-0003","HFTASK-0010"]),
        mk("HFTASK-0022", "RuVocal (meta/RuVector/ui) - THE real front door, prompt_hub-integrated", Priority::P1,
           "ADR-0001 §11/§12/R14: RuVocal (~/Desktop/meta/RuVector/ui) is the REAL chosen front door (an unmodified HuggingFace Chat-UI fork, SvelteKit, with an mcp-bridge/ subpackage; nothing consumes loop events yet). NOTE: the envctl/loop-forge zellij multi-pane dashboard was attempted and FAILED - do NOT revive it; RuVocal is the surface. Adopt-and-extend RuVocal: integrate prompt_hub (vibe request in -> dispatch via the seam HFTASK-0019/HFTASK-0003) -> surface loop state (HFTASK-0020) + delivery result (HFTASK-0021) back in chat via mcp-bridge.", &["HFTASK-0019","HFTASK-0020","HFTASK-0003"]),
    ];
    // HFTASK-0026 carries a precise path_scope (["handoff/**"]) and a routing-specific
    // acceptance criterion, so it is built directly rather than via `mk` (whose fixed
    // path_scope/acceptance template doesn't fit a kernel-internal CORRECTNESS fix).
    let mut backlog = backlog;
    {
        let id = "HFTASK-0026";
        let title =
            "Anchor hf core ledger ops to meta-root + kernel/fleet routing (fix kb-mint contamination)";
        let objective = "ADR-0004 §3 two-ledger residency: hf resolved .handoff/ledger.db + tasks/ CWD-relative with no anchoring, so `hf task mint --from-kb` + claim/checkpoint/done run from handoff/ wrote envctl-domain KBTASK cards into handoff's KERNEL ledger instead of the FLEET ledger (meta/.handoff). Add route_for_task(id) (LOCAL card -> KERNEL home; else FLEET card -> meta/.handoff; else FAIL CLOSED) and route every per-task ledger op (claim/checkpoint/done/review verdict/ship) through it; mint kb cards to the FLEET tasks dir via find_meta_root(). Global/self ops (status/resume/handoff/drift) stay LOCAL.";
        let path_scope = vec!["handoff/**".to_string()];
        let acceptance = vec![
            "kb-minted cards land in the FLEET tasks dir (meta/.handoff/tasks); per-task ops route to the home the card lives in; an unknown task id fails closed (no ledger created); KERNEL ops from handoff/ still hit the KERNEL ledger; cargo test + fmt + clippy green"
                .to_string(),
        ];
        backlog.push(WorkOrder {
            schema: "handoff.task.v1".into(),
            id: id.into(),
            title: title.into(),
            status: Status::Backlog,
            priority: Priority::P0,
            objective: objective.into(),
            path_scope: path_scope.clone(),
            acceptance_criteria: acceptance.clone(),
            test_commands: vec!["cargo test".into()],
            dependencies: vec![],
            blocked_by: vec![],
            allows_network: false,
            allows_dependency_addition: false,
            correlation_id: "handoff-buildout".into(),
            role: Some("implementer".into()),
            intent_lock: WorkOrder::compute_intent_lock(objective, &path_scope, &acceptance),
        });
    }
    // HFTASK-0027/0028: ledger-robustness hardening after the contamination + staleness
    // investigation. Both carry precise handoff-scoped path_scope + targeted acceptance,
    // so (like HFTASK-0026) they are built directly rather than via the `mk` template.
    {
        let id = "HFTASK-0027";
        let title = "hf resume recomputes live witnessed count (fix stale packet-cached display)";
        let objective = "CONFIRMED stale-read: `hf resume` (ResumeMode::Full) echoed packets/latest.md verbatim, freezing 'Tamper-evident events verified: N' + Done N/M at the last `hf handoff` (showed 336 while the live ledger had 371; witness chain INTACT — not corruption). Fix: render the packet LIVE on every `hf resume` from ledger_path() (verify_witness_chain for the count) + current_statuses()/load_tasks() (Done N/M), via the same renderer as `hf handoff`, instead of reading the frozen file. Do NOT change `hf handoff` rendering.";
        let path_scope = vec!["handoff/**".to_string()];
        let acceptance = vec![
            "hf resume witnessed count == live ledger count == hf handoff verified count; reflects new events without hf handoff"
                .to_string(),
        ];
        backlog.push(WorkOrder {
            schema: "handoff.task.v1".into(),
            id: id.into(),
            title: title.into(),
            status: Status::Backlog,
            priority: Priority::P1,
            objective: objective.into(),
            path_scope: path_scope.clone(),
            acceptance_criteria: acceptance.clone(),
            test_commands: vec!["cargo test".into()],
            dependencies: vec![],
            blocked_by: vec![],
            allows_network: false,
            allows_dependency_addition: false,
            correlation_id: "handoff-buildout".into(),
            role: Some("implementer".into()),
            intent_lock: WorkOrder::compute_intent_lock(objective, &path_scope, &acceptance),
        });
    }
    {
        let id = "HFTASK-0028";
        let title = "Serialize concurrent hf ledger writes (WAL + busy_timeout + BEGIN IMMEDIATE)";
        let objective = "HAZARD: multiple concurrent `hf` processes (two handoff sessions, or a session + a PostEdit checkpoint hook) write the same .handoff/ledger.db; interleaving risks 'database is locked' or a forked/desynced witness chain. Fix in Ledger::open + the append path: set journal_mode=WAL + busy_timeout=5000, and wrap the event append in a BEGIN IMMEDIATE transaction that reads the latest prev_hash INSIDE the transaction and inserts atomically, so concurrent writers serialize (block-and-retry) and can never both chain off the same prev.";
        let path_scope = vec!["handoff/**".to_string()];
        let acceptance = vec![
            "two concurrent hf checkpoint procs both succeed + witness chain verifies".to_string(),
        ];
        backlog.push(WorkOrder {
            schema: "handoff.task.v1".into(),
            id: id.into(),
            title: title.into(),
            status: Status::Backlog,
            priority: Priority::P1,
            objective: objective.into(),
            path_scope: path_scope.clone(),
            acceptance_criteria: acceptance.clone(),
            test_commands: vec!["cargo test".into()],
            dependencies: vec![],
            blocked_by: vec![],
            allows_network: false,
            allows_dependency_addition: false,
            correlation_id: "handoff-buildout".into(),
            role: Some("implementer".into()),
            intent_lock: WorkOrder::compute_intent_lock(objective, &path_scope, &acceptance),
        });
    }
    {
        let id = "HFTASK-0029";
        let title = "hf hygiene: ship stages only task scope + seed idempotent + claim exits nonzero when blocked";
        let objective = "Surgical hf hygiene bundle (3 located defects, all in hf/src/main.rs): (A) `hf ship` did `git add -A`, sweeping untracked KBTASK cards + _workspace/ scratch into PR #29 — stage ONLY tracked modifications (`git add -u`) plus the task's own card. (B) `hf seed` wrote every card with hardcoded Status::Backlog, overwriting existing cards so re-seed reset done cards (HFTASK-0001..0020) to backlog — make seed additive: only write MISSING cards, preserving existing status. (C) `hf claim` printed BLOCKED to stderr but `return`ed with exit 0 — a blocked claim must exit nonzero so hooks/scripts/the loop see the failure, while `hf dispatch`'s internal claim loop keeps its skip-and-continue semantics.";
        let path_scope = vec!["handoff/**".to_string()];
        let acceptance = vec![
            "ship excludes untracked; seed preserves done status; claim exits nonzero when blocked"
                .to_string(),
        ];
        backlog.push(WorkOrder {
            schema: "handoff.task.v1".into(),
            id: id.into(),
            title: title.into(),
            status: Status::Backlog,
            priority: Priority::P1,
            objective: objective.into(),
            path_scope: path_scope.clone(),
            acceptance_criteria: acceptance.clone(),
            test_commands: vec!["cargo test".into()],
            dependencies: vec![],
            blocked_by: vec![],
            allows_network: false,
            allows_dependency_addition: false,
            correlation_id: "handoff-buildout".into(),
            role: Some("implementer".into()),
            intent_lock: WorkOrder::compute_intent_lock(objective, &path_scope, &acceptance),
        });
    }
    {
        let id = "HFTASK-0030";
        let title = "preflight mirrors each repo's CI clippy flags (--all-targets gap that failed PR #30) + loop agents run --all-targets";
        let objective = "Defect D (cross-workspace): the shared pre-push gate scripts/preflight.sh ran `cargo clippy --all-features` with NO --all-targets, assuming --all-targets is always stricter than CI. That is FALSE for repos whose CI uses --all-targets (handoff: `cargo clippy --workspace --all-targets -- -D warnings`). --all-targets lints TEST code; without mirroring it a test-code lint (needless &borrow in a #[cfg(test)] assert) passed preflight but FAILED CI (PR #30). Fix: (meta repo) preflight greps each repo's .github/workflows/*.yml clippy line and mirrors --all-targets only when that repo's CI uses it (per-repo subset-mirror; a blanket --all-targets would false-block repos whose CI omits it; preserve the --all-features default-features fallback on the --all-features axis only). (handoff repo) the loop's kernel-verifier + kernel-implementer agents mandate `cargo clippy --workspace --all-targets -- -D warnings` to match handoff CI exactly, and CLAUDE.md documents that handoff CI uses --all-targets.";
        let path_scope = vec!["handoff/**".to_string()];
        let acceptance = vec![
            "preflight runs --all-targets where the repo's CI does; kernel-verifier/implementer mandate --all-targets"
                .to_string(),
        ];
        backlog.push(WorkOrder {
            schema: "handoff.task.v1".into(),
            id: id.into(),
            title: title.into(),
            status: Status::Backlog,
            priority: Priority::P1,
            objective: objective.into(),
            path_scope: path_scope.clone(),
            acceptance_criteria: acceptance.clone(),
            test_commands: vec!["cargo test".into()],
            dependencies: vec![],
            blocked_by: vec![],
            allows_network: false,
            allows_dependency_addition: false,
            correlation_id: "handoff-buildout".into(),
            role: Some("implementer".into()),
            intent_lock: WorkOrder::compute_intent_lock(objective, &path_scope, &acceptance),
        });
    }
    // HFTASK-0029 Defect B: seed is IDEMPOTENT/ADDITIVE — only write cards that are
    // MISSING on disk. Overwriting an existing card clobbered its live status (done →
    // backlog) on re-seed; skipping existing cards preserves status and still creates
    // newly-added seed cards.
    let mut written = 0usize;
    let mut skipped = 0usize;
    for wo in &backlog {
        if tasks_dir().join(format!("{}.task.json", wo.id)).exists() {
            skipped += 1;
        } else {
            save_task(wo);
            written += 1;
        }
    }
    println!(
        "hf seed: wrote {written} new task card(s) (skipped {skipped} existing) to {}/",
        tasks_dir().display()
    );
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.first().map(|s| s.as_str()) {
        Some("init") => cmd_init(),
        Some("seed") => cmd_seed(),
        Some("status") => cmd_status(args.iter().any(|a| a == "--json")),
        Some("claim") => cmd_claim(args.get(1).map(|s| s.as_str()).unwrap_or("")),
        Some("release") => cmd_release(args.get(1).map(|s| s.as_str()).unwrap_or("")),
        Some("checkpoint") => {
            let auto = args.iter().any(|a| a == "--auto");
            let quiet = args.iter().any(|a| a == "--quiet");
            let positional: Vec<&str> = args[1..]
                .iter()
                .map(|s| s.as_str())
                .filter(|a| !a.starts_with("--"))
                .collect();
            let id = positional.first().copied();
            let note = positional.get(1..).map(|r| r.join(" ")).unwrap_or_default();
            cmd_checkpoint(id, &note, auto, quiet);
            if args.iter().any(|a| a == "--sync-cards") {
                let n = sync_cards();
                if !quiet {
                    println!("hf checkpoint: synced {n} card(s) from ledger truth");
                }
            }
        }
        Some("sync-cards") => {
            let n = sync_cards();
            println!("hf sync-cards: synced {n} card(s) from ledger truth");
        }
        Some("sync") => {
            let auto = args.iter().any(|a| a == "--auto");
            let dry = args.iter().any(|a| a == "--dry-run");
            sync::cmd_sync(auto, dry);
        }
        Some("done") => {
            let id = args.get(1).map(|s| s.as_str()).unwrap_or("");
            let pr = args
                .iter()
                .position(|a| a == "--pr")
                .and_then(|i| args.get(i + 1))
                .map(|s| s.as_str());
            cmd_done(id, pr);
        }
        Some("task") if args.get(1).map(|s| s.as_str()) == Some("mint") => {
            let slug = args
                .iter()
                .position(|a| a == "--from-kb")
                .and_then(|i| args.get(i + 1))
                .map(|s| s.as_str())
                .unwrap_or("");
            kb::cmd_mint_from_kb(slug);
        }
        Some("intake") => {
            let flag = |name: &str| {
                args.iter()
                    .position(|a| a == name)
                    .and_then(|i| args.get(i + 1))
                    .map(|s| s.as_str())
            };
            let scope: Option<Vec<String>> = flag("--scope").map(|s| {
                s.split(',')
                    .map(|g| g.trim().to_string())
                    .filter(|g| !g.is_empty())
                    .collect()
            });
            intake::cmd_intake(
                flag("--bundle"),
                flag("--vibe"),
                flag("--intent"),
                scope.as_deref(),
            );
        }
        Some("dispatch") => {
            let next_only = args.iter().any(|a| a == "--next");
            let cid = args
                .get(1)
                .map(|s| s.as_str())
                .filter(|s| !s.starts_with("--"));
            intake::cmd_dispatch(cid, next_only);
        }
        Some("ship") => {
            let id = args.get(1).map(|s| s.as_str()).unwrap_or("");
            let base = args
                .iter()
                .position(|a| a == "--base")
                .and_then(|i| args.get(i + 1))
                .map(|s| s.as_str())
                .unwrap_or("master");
            cmd_ship(id, base);
        }
        Some("review") if args.get(1).map(|s| s.as_str()) == Some("verdict") => {
            let by = args
                .iter()
                .position(|a| a == "--by")
                .and_then(|i| args.get(i + 1))
                .map(|s| s.as_str())
                .unwrap_or("unattributed");
            cmd_review_verdict(
                args.get(2).map(|s| s.as_str()).unwrap_or(""),
                args.get(3).map(|s| s.as_str()).unwrap_or(""),
                args.get(4).map(|s| s.as_str()).unwrap_or(""),
                by,
            );
        }
        Some("session") => session::cmd_session(&args[1..]),
        Some("drift") => gates::cmd_drift(args.iter().any(|a| a == "--json")),
        Some("policy")
            if args
                .get(1)
                .map(|s| s.as_str())
                .is_some_and(|s| s.starts_with("check-")) =>
        {
            let kind = args.get(1).map(|s| s.as_str()).unwrap_or("");
            gates::cmd_policy_check(kind, args.iter().any(|a| a == "--json"));
        }
        Some("fleet") if args.get(1).map(|s| s.as_str()) == Some("status") => {
            fleet::cmd_fleet_status(args.iter().any(|a| a == "--json"));
        }
        Some("fleet") if args.get(1).map(|s| s.as_str()) == Some("render") => {
            // hf fleet render <member> — compile <member>'s packet from the FLEET ledger
            let member = args.get(2).map(|s| s.as_str()).unwrap_or("");
            if member.is_empty() {
                eprintln!("hf fleet render <member> — member name required");
                std::process::exit(2);
            }
            match fleet::find_meta_root() {
                Some(root) => match fleet::render_member_packet(&root, member) {
                    Ok(p) => println!("hf fleet render: wrote {}", p.display()),
                    Err(e) => {
                        eprintln!("hf fleet render: {e}");
                        std::process::exit(1);
                    }
                },
                None => {
                    eprintln!(
                        "hf fleet render: no .meta.yaml found from the current directory upward"
                    );
                    std::process::exit(1);
                }
            }
        }
        Some("handoff") => cmd_handoff(),
        Some("resume") => {
            let mode = if args.iter().any(|a| a == "--json") {
                ResumeMode::Json
            } else if args.iter().any(|a| a == "--compact") {
                ResumeMode::Compact
            } else {
                ResumeMode::Full
            };
            cmd_resume(mode);
        }
        _ => {
            eprintln!("hf <init|seed|status [--json]|session start|end [--recycle]|claim ID|release ID|checkpoint ID [note] [--auto] [--quiet] [--sync-cards]|sync-cards|sync [--auto] [--dry-run]|done ID [--pr N]|task mint --from-kb SLUG|intake --bundle FILE [--vibe TEXT] [--intent FILE] [--scope a,b]|dispatch WORKFLOW_ID [--next]|ship ID [--base BR]|review verdict ID PR approve|deny [--by WHO]|drift [--json]|policy check-claim|check-edit|check-handoff [--json]|fleet status [--json]|fleet render MEMBER|handoff|resume [--json|--compact]>");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use work_order::{work_orders_from_bundle, SwarmBundle};

    fn sample_tasks() -> Vec<WorkOrder> {
        work_orders_from_bundle(&SwarmBundle {
            workflow_id: "wf-test".into(),
            role_prompts: vec![
                ("architect".into(), "design".into()),
                ("coder".into(), "build".into()),
            ],
            handoff_template: "standard".into(),
            consistency_report: vec![],
            evolution_suggestions: vec![],
        })
    }

    /// FIX-2 regression: the summary's witnessed count is exactly the count it is given —
    /// resume/handoff compute it live from the ledger, never echo a stale packet value.
    #[test]
    fn summary_reports_the_witness_count_it_is_given() {
        let tasks = sample_tasks();
        let replay: Vec<(String, Status)> = vec![];
        let s = summary_json(&tasks, &replay, 42);
        assert_eq!(s["witnessed_events_verified"], 42);
        // a different witness count must flow straight through (no caching/staleness)
        let s2 = summary_json(&tasks, &replay, 43);
        assert_eq!(s2["witnessed_events_verified"], 43);
    }

    /// HFTASK-0027: the packet renderer (now shared by `hf handoff` AND the live
    /// `hf resume` Full path) reflects exactly the Done N/M + witness count it is given.
    /// Because `ResumeMode::Full` calls this with values recomputed from the ledger on
    /// every invocation — instead of echoing packets/latest.md — resume can never show a
    /// stale count: feeding two different live counts yields two different "Progress" lines.
    #[test]
    fn packet_renderer_reflects_live_done_and_witness_count() {
        let tasks = sample_tasks();
        let replay = vec![(tasks[0].id.clone(), Status::Done)];

        let md_336 = render_packet_md(&tasks, &replay, 336);
        assert!(
            md_336.contains("Done: 1/2.  Tamper-evident events verified: 336."),
            "renderer must emit the given count; got:\n{md_336}"
        );

        // Simulate events appended since the last handoff (live recount -> 371):
        // the rendered Progress line must change, proving no frozen/cached value.
        let md_371 = render_packet_md(&tasks, &replay, 371);
        assert!(
            md_371.contains("Tamper-evident events verified: 371."),
            "renderer must reflect the new live count; got:\n{md_371}"
        );
        assert!(!md_371.contains("verified: 336."));

        // And Done N/M is live too: marking both Done flips the progress numerator.
        let replay_both = vec![
            (tasks[0].id.clone(), Status::Done),
            (tasks[1].id.clone(), Status::Done),
        ];
        let md_both = render_packet_md(&tasks, &replay_both, 371);
        assert!(md_both.contains("Done: 2/2."));
    }

    #[test]
    fn summary_counts_done_vs_remaining_and_picks_next() {
        let tasks = sample_tasks();
        // mark the first task Done via replay; the second is the next safe task
        let replay = vec![(tasks[0].id.clone(), Status::Done)];
        let s = summary_json(&tasks, &replay, 7);
        assert_eq!(s["tasks_total"], 2);
        assert_eq!(s["done"].as_array().unwrap().len(), 1);
        assert_eq!(s["remaining"].as_array().unwrap().len(), 1);
        assert_eq!(s["next_task_id"], serde_json::json!(tasks[1].id));
        assert_eq!(
            s["next_command"],
            serde_json::json!(format!("hf claim {}", tasks[1].id))
        );
    }

    // --- HFTASK-0029 hygiene bundle ---------------------------------------------------

    use crate::test_support::cwd_lock;

    /// Build a minimal valid card for a given id/status (test fixture).
    fn card(id: &str, status: Status) -> WorkOrder {
        let objective = format!("objective for {id}");
        let path_scope = vec!["handoff/**".to_string()];
        let acceptance = vec!["done".to_string()];
        WorkOrder {
            schema: "handoff.task.v1".into(),
            id: id.into(),
            title: format!("title {id}"),
            status,
            priority: Priority::P1,
            objective: objective.clone(),
            path_scope: path_scope.clone(),
            acceptance_criteria: acceptance.clone(),
            test_commands: vec!["cargo test".into()],
            dependencies: vec![],
            blocked_by: vec![],
            allows_network: false,
            allows_dependency_addition: false,
            correlation_id: "test".into(),
            role: None,
            intent_lock: WorkOrder::compute_intent_lock(&objective, &path_scope, &acceptance),
        }
    }

    /// A leaser whose reservation outcome is fixed — drives the claim gate in tests.
    struct StubLeaser(lease::Reserve);
    impl lease::Leaser for StubLeaser {
        fn reserve(&self, _resource: &str, _ttl: u64, _note: &str) -> lease::Reserve {
            self.0.clone()
        }
        fn release(&self, _resource: &str) -> bool {
            true
        }
    }

    /// Make a temp dir + cd into it (cwd-locked); returns the dir and the previous cwd so
    /// the caller restores it. `.handoff/tasks` is created (the LOCAL/KERNEL home).
    fn temp_cwd(tag: &str) -> (PathBuf, PathBuf) {
        let mut tmp = std::env::temp_dir();
        tmp.push(format!("hf-0029-{tag}-{}-{}", std::process::id(), now_ns()));
        fs::create_dir_all(tmp.join(HF).join("tasks")).unwrap();
        let tmp = tmp.canonicalize().unwrap();
        let prev = std::env::current_dir().unwrap();
        std::env::set_current_dir(&tmp).unwrap();
        (tmp, prev)
    }

    /// AC-A: ship stages ONLY `git add -u` (no untracked) + the task's own card; an
    /// untracked junk file is never in the stage set, so it can't be swept into the PR.
    #[test]
    fn ship_stage_specs_excludes_untracked_and_includes_card() {
        let _g = cwd_lock();
        let (tmp, prev) = temp_cwd("ship");
        // task card present on disk; an untracked junk file also present.
        save_task(&card("HFTASK-9101", Status::Claimed));
        fs::write("junk-untracked.txt", "scratch").unwrap();

        let specs = ship_stage_specs("HFTASK-9101");
        std::env::set_current_dir(&prev).unwrap();

        // -u = tracked modifications/deletions only (NO untracked).
        assert!(specs.iter().any(|s| s == "-u"), "must stage tracked via -u");
        // the task's own card is staged explicitly.
        assert!(
            specs.contains(&task_card_relpath("HFTASK-9101")),
            "card must be staged; got {specs:?}"
        );
        // NOTHING ever stages the untracked junk file or `-A`/`.`.
        assert!(!specs.iter().any(|s| s.contains("junk-untracked")));
        assert!(!specs.iter().any(|s| s == "-A" || s == "."));
        let _ = fs::remove_dir_all(tmp);
    }

    /// AC-A (corollary): with no card on disk, ship stages only `-u` — never a wildcard.
    #[test]
    fn ship_stage_specs_without_card_is_just_tracked() {
        let _g = cwd_lock();
        let (tmp, prev) = temp_cwd("ship-nocard");
        let specs = ship_stage_specs("HFTASK-NOPE");
        std::env::set_current_dir(&prev).unwrap();
        assert_eq!(specs, vec!["-u".to_string()]);
        let _ = fs::remove_dir_all(tmp);
    }

    /// AC-B: re-seeding must NOT clobber an existing card's status. We simulate seed's
    /// additive write: a pre-existing `done` card is preserved (skipped), a missing card
    /// is written.
    #[test]
    fn seed_is_additive_and_preserves_existing_status() {
        let _g = cwd_lock();
        let (tmp, prev) = temp_cwd("seed");
        // Pre-existing card with status DONE.
        save_task(&card("HFTASK-0001", Status::Done));
        // A would-be seed value for the SAME id, but as Backlog (the clobbering value).
        let reseed_existing = card("HFTASK-0001", Status::Backlog);
        let new_card = card("HFTASK-9999", Status::Backlog);

        // Replicate cmd_seed's additive loop: only write MISSING cards.
        for wo in [&reseed_existing, &new_card] {
            if !tasks_dir().join(format!("{}.task.json", wo.id)).exists() {
                save_task(wo);
            }
        }

        let kept = load_task_in(&tasks_dir(), "HFTASK-0001").unwrap();
        let created = load_task_in(&tasks_dir(), "HFTASK-9999");
        std::env::set_current_dir(&prev).unwrap();

        assert_eq!(
            kept.status,
            Status::Done,
            "existing done card must be preserved, not reset to backlog"
        );
        assert!(created.is_some(), "a missing seed card must be created");
        assert_eq!(created.unwrap().status, Status::Backlog);
        let _ = fs::remove_dir_all(tmp);
    }

    /// AC-C: a blocked/refused claim returns `false` (→ CLI exits nonzero); a successful
    /// claim returns `true` (→ exit 0). Driven via a stub leaser so no real mesh/process.
    #[test]
    fn claim_returns_false_when_blocked_true_when_acquired() {
        let _g = cwd_lock();
        let (tmp, prev) = temp_cwd("claim");
        save_task(&card("HFTASK-9201", Status::Backlog));

        // Refused (peer holds the lease) → false.
        let blocked = cmd_claim_with(
            "HFTASK-9201",
            &StubLeaser(lease::Reserve::Conflict("held by peer-x".into())),
        );
        // Acquired → true (records the ledger transition into the temp KERNEL home).
        let ok = cmd_claim_with("HFTASK-9201", &StubLeaser(lease::Reserve::Acquired));
        std::env::set_current_dir(&prev).unwrap();

        assert!(
            !blocked,
            "a blocked claim must return false (CLI exits nonzero)"
        );
        assert!(ok, "a successful claim must return true (CLI exits 0)");
        let _ = fs::remove_dir_all(tmp);
    }
}
