//! `hf sync` (HFTASK-0011, ADR-0001 §6 / ADR-0003 rule 3) — two idempotent, one-way
//! maintenance passes, meant for session-end / post-merge:
//!
//!   Part A — registration ensure/repair: confirm this repo's membership in the meta
//!   workspace (`../.meta.yaml`) and de-duplicate its `../.gitignore` ignore line.
//!   Grep-guarded — never blind-append; there is no `meta project add`.
//!
//!   Part B — `.kb` mirror: write ledger-derived bodies INTO the planning plane,
//!   scoped to the generated slugs `context/overridable/{active,progress}` only.
//!   **ONE-WAY:** kb is never read back as execution truth; immutable/extensible/tasks
//!   slugs are never touched. Degrades (and says so) when `.kb`/`git-kb` is absent.
//!
//! `--dry-run` prints what Part B would write without creating/committing anything.

use crate::PrioStr;
use std::path::Path;
use std::process::Command;
use work_order::{Status, WorkOrder};

const MIRROR_SLUGS: [(&str, &str); 2] = [
    ("context/overridable/active", "Active Context"),
    ("context/overridable/progress", "Progress"),
];
const GEN_TAG: &str = "<!-- generated by `hf sync` from ledger truth — do not hand-edit (ONE-WAY ledger→kb) -->";

pub fn cmd_sync(auto: bool, dry_run: bool) {
    let _ = auto; // accepted for the hook contract (hf sync --auto); behavior is identical
    let Some(root) = crate::fleet::find_meta_root() else {
        eprintln!("hf sync: no .meta.yaml found from the current directory upward");
        std::process::exit(1);
    };
    let repo_name = std::env::current_dir()
        .ok()
        .and_then(|p| p.file_name().map(|s| s.to_string_lossy().into_owned()))
        .unwrap_or_default();

    part_a_registration(&root, &repo_name, dry_run);
    part_b_kb_mirror(&root, &repo_name, dry_run);
}

// --- Part A -----------------------------------------------------------------

/// True if `.gitignore` line, normalized, is this repo's ignore entry (`name`, `name/`,
/// `/name`, `/name/`).
fn is_repo_ignore(line: &str, repo: &str) -> bool {
    let t = line.trim();
    let t = t.trim_start_matches('/').trim_end_matches('/');
    t == repo
}

/// De-duplicate a repo's ignore line, keeping the first. Pure → testable. Returns the
/// (possibly unchanged) content and whether anything changed.
fn dedup_gitignore(content: &str, repo: &str) -> (String, bool) {
    let mut seen = false;
    let mut changed = false;
    let mut out = String::new();
    for line in content.lines() {
        if is_repo_ignore(line, repo) {
            if seen {
                changed = true;
                continue;
            }
            seen = true;
        }
        out.push_str(line);
        out.push('\n');
    }
    (out, changed)
}

fn part_a_registration(root: &Path, repo: &str, dry: bool) {
    let meta_yaml = std::fs::read_to_string(root.join(".meta.yaml")).unwrap_or_default();
    let needle = format!("  {repo}:");
    let registered = meta_yaml
        .lines()
        .any(|l| l.trim_end() == needle || l.starts_with(&needle));

    let gi_path = root.join(".gitignore");
    let gi = std::fs::read_to_string(&gi_path).unwrap_or_default();
    let present = gi.lines().any(|l| is_repo_ignore(l, repo));
    let (deduped, changed) = dedup_gitignore(&gi, repo);
    if changed && !dry {
        let _ = std::fs::write(&gi_path, &deduped);
    }

    println!(
        "hf sync [A] {repo}: .meta.yaml={} .gitignore={}{}",
        if registered { "registered" } else { "MISSING (add manually — no meta project add)" },
        if present { "ignored" } else { "MISSING" },
        match (changed, dry) {
            (true, true) => " (duplicate ignore line would be removed)",
            (true, false) => " (duplicate ignore line removed)",
            _ => "",
        }
    );
}

// --- Part B -----------------------------------------------------------------

fn run_git_kb(root: &Path, args: &[&str]) -> Result<String, String> {
    match Command::new("git-kb").args(args).current_dir(root).output() {
        Ok(o) if o.status.success() => Ok(String::from_utf8_lossy(&o.stdout).into_owned()),
        Ok(o) => Err(format!(
            "git-kb {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&o.stderr).trim()
        )),
        Err(e) => Err(format!("git-kb not runnable: {e}")),
    }
}

fn git_kb_available(root: &Path) -> bool {
    Command::new("git-kb")
        .arg("--version")
        .current_dir(root)
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

fn status_of<'a>(card: &'a WorkOrder, replay: &'a [(String, Status)]) -> Status {
    replay
        .iter()
        .find(|(k, _)| k == &card.id)
        .map(|(_, s)| *s)
        .unwrap_or(card.status)
}

/// Ledger-derived "progress" body. Pure → testable.
fn progress_body(repo: &str, tasks: &[WorkOrder], replay: &[(String, Status)]) -> String {
    let done = tasks.iter().filter(|t| status_of(t, replay) == Status::Done).count();
    let mut s = format!("{GEN_TAG}\n\n## Progress — {repo}\n\nDone: {done}/{}.\n\n### Open cards\n", tasks.len());
    for t in tasks.iter().filter(|t| status_of(t, replay) != Status::Done) {
        s.push_str(&format!("- [{}] {} — {}\n", t.priority_str(), t.id, t.title));
    }
    s
}

/// Ledger-derived "active" body. `next_desc` is the next-safe task (computed by the
/// caller via the kernel's dependency-aware `next_safe`, so the mirror matches
/// `hf resume`). Pure → testable.
fn active_body(repo: &str, next_desc: &str) -> String {
    format!("{GEN_TAG}\n\n## Active — {repo}\n\nNext: {next_desc}\nResume: `hf resume`\n")
}

/// Keep the existing frontmatter block (preserving the id), else synthesize a minimal
/// one. Pure → testable.
fn preserve_frontmatter(existing: &str, slug: &str, title: &str) -> String {
    let mut lines = existing.lines();
    if lines.next().map(str::trim) == Some("---") {
        let mut fm = String::from("---\n");
        for line in lines {
            fm.push_str(line);
            fm.push('\n');
            if line.trim() == "---" {
                return fm;
            }
        }
    }
    format!("---\nslug: {slug}\ntitle: \"{title}\"\ntype: context\nstatus: active\n---\n")
}

fn mirror_slug(root: &Path, slug: &str, title: &str, body: &str) -> Result<(), String> {
    if run_git_kb(root, &["show", slug]).is_err() {
        run_git_kb(root, &["create", "context", "--slug", slug, "--title", title])?;
    }
    run_git_kb(root, &["checkout", slug])?;
    let ws = root
        .join(".kb/workspaces/main")
        .join(format!("{slug}.md"));
    let cur = std::fs::read_to_string(&ws).unwrap_or_default();
    let fm = preserve_frontmatter(&cur, slug, title);
    std::fs::write(&ws, format!("{fm}\n{body}\n")).map_err(|e| e.to_string())?;
    run_git_kb(root, &["commit", "-m", &format!("hf sync: mirror ledger truth → {slug}")])?;
    Ok(())
}

fn part_b_kb_mirror(root: &Path, repo: &str, dry: bool) {
    if !root.join(".kb").is_dir() || !git_kb_available(root) {
        println!("hf sync [B] kb mirror skipped — no .kb or git-kb unavailable (degrade-and-say-so)");
        return;
    }
    let tasks = crate::load_tasks();
    let replay = crate::current_statuses();
    let next_desc = crate::next_safe(&tasks, &replay)
        .map(|t| format!("{} — {}", t.id, t.title))
        .unwrap_or_else(|| "(no open cards)".into());
    let bodies = [
        (MIRROR_SLUGS[0].0, MIRROR_SLUGS[0].1, active_body(repo, &next_desc)),
        (MIRROR_SLUGS[1].0, MIRROR_SLUGS[1].1, progress_body(repo, &tasks, &replay)),
    ];
    for (slug, title, body) in &bodies {
        if dry {
            println!("hf sync [B] DRY would mirror {slug}:\n{body}");
            continue;
        }
        match mirror_slug(root, slug, title, body) {
            Ok(()) => println!("hf sync [B] mirrored {slug} (one-way ledger→kb)"),
            Err(e) => eprintln!("hf sync [B] {slug} failed: {e}"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dedup_keeps_first_ignore_line() {
        let gi = "node_modules/\nhandoff/\nfoo\nhandoff/\n";
        let (out, changed) = dedup_gitignore(gi, "handoff");
        assert!(changed);
        assert_eq!(out.matches("handoff/").count(), 1);
        assert!(out.contains("node_modules/"));
    }

    #[test]
    fn dedup_noop_when_single() {
        let gi = "handoff/\nfoo\n";
        let (_, changed) = dedup_gitignore(gi, "handoff");
        assert!(!changed);
    }

    #[test]
    fn frontmatter_preserved_with_id() {
        let existing = "---\nid: 019e-abc\nslug: context/overridable/active\ntitle: \"Active Context\"\n---\nold body\n";
        let fm = preserve_frontmatter(existing, "context/overridable/active", "Active Context");
        assert!(fm.contains("id: 019e-abc"));
        assert!(fm.trim_end().ends_with("---"));
        assert!(!fm.contains("old body"));
    }

    #[test]
    fn frontmatter_synthesized_when_absent() {
        let fm = preserve_frontmatter("no frontmatter here", "context/overridable/progress", "Progress");
        assert!(fm.contains("slug: context/overridable/progress"));
    }

    #[test]
    fn bodies_carry_generated_tag_and_are_one_way() {
        let p = progress_body("handoff", &[], &[]);
        let a = active_body("handoff", "HFTASK-0011 — hf sync");
        assert!(p.contains("generated by `hf sync`"));
        assert!(a.contains("generated by `hf sync`"));
        assert!(a.contains("HFTASK-0011 — hf sync"));
        assert!(p.contains("Done: 0/0"));
    }
}
